/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuildInfo { 
    commitHash?: string;
    branchName?: string;
    versionNumber?: string;
    buildTime?: string;
    commitTime?: string;
    moduleName?: string;
}

