/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
 */
export const Currency = {
    Eur: 'EUR',
    Usd: 'USD',
    Gbp: 'GBP',
    Chf: 'CHF',
    Pln: 'PLN'
} as const;
export type Currency = typeof Currency[keyof typeof Currency];

