/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the direction of the transaction, either selling or buying currency.
 */
export const Direction = {
    Sell: 'SELL',
    Buy: 'BUY'
} as const;
export type Direction = typeof Direction[keyof typeof Direction];

