/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorObjectResponse { 
    /**
     * A code representing the type of error
     */
    errorCode?: string;
    /**
     * A unique identifier for the error instance
     */
    errorId?: string;
    /**
     * A descriptive message explaining the error
     */
    message?: string;
    /**
     * The timestamp when the error occurred, recorded in UTC timezone
     */
    timestampUtc?: string;
}

