/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of event associated with a transaction, such as deposit, withdrawal, or exchange.
 */
export const EventType = {
    Deposit: 'DEPOSIT',
    Withdraw: 'WITHDRAW',
    Order: 'ORDER',
    Exchange: 'EXCHANGE',
    Correction: 'CORRECTION',
    Fee: 'FEE',
    Cancel: 'CANCEL'
} as const;
export type EventType = typeof EventType[keyof typeof EventType];

