/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Direction } from './direction';
import { Pair } from './pair';


export interface ExchangeEvent { 
    /**
     * Unique identifier for the exchange event
     */
    id: number;
    /**
     * Trading pair associated with the exchange event
     */
    pair: Pair;
    /**
     * Value involved in the exchange event
     */
    amount: number;
    /**
     * Value exchanged in the exchange event.For full exchange value is equal to \'amount\' field;
     */
    amountRealized: number;
    /**
     * Direction of the exchange event (buy/sell)
     */
    direction: Direction;
    /**
     * Ratio for the exchange event
     */
    ratio: number;
    /**
     * Date and time when the exchange occurred, in UTC timezone
     */
    dateUtc: string;
}
export namespace ExchangeEvent {
}


