/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderBookRow } from './orderBookRow';
import { Pair } from './pair';


export interface OrderBookData { 
    /**
     * pair
     */
    p?: Pair;
    /**
     * is full order book or partial
     */
    f?: boolean;
    /**
     * buy order book
     */
    b: Array<OrderBookRow>;
    /**
     * sell order book
     */
    s: Array<OrderBookRow>;
}
export namespace OrderBookData {
}


