/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderBookRow { 
    /**
     * ratio of currency
     */
    r: number;
    /**
     * amount of currency
     */
    a: number;
}

