/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Direction } from './direction';
import { Pair } from './pair';


export interface Order { 
    /**
     * A unique identifier for the order, represented as a UUID.
     */
    id: string;
    /**
     * The currency pair associated with the order.
     */
    pair: Pair;
    /**
     * The monetary value of the order, represented as a 64-bit integer.
     */
    amount?: number;
    /**
     * The direction of the order (buy or sell).
     */
    direction: Direction;
    /**
     * The exchange ratio for the order, represented as a 64-bit integer.
     */
    ratio: number;
    /**
     * An optional field to specify the event type related to the order.
     */
    event?: string;
    /**
     * The IP address of the user making the order.
     */
    ip?: string;
    /**
     * The identifier of the user who placed the order.
     */
    user?: string;
    /**
     * A hash value for the order, represented as a 64-bit integer.
     */
    hash?: number;
    /**
     * A flag indicating whether the order is logged in the journal.
     */
    journal?: boolean;
    /**
     * A flag indicating whether the financial aspects of the order have been checked.
     */
    checkedFinance?: boolean;
    /**
     * A flag indicating whether the order data has been marshalled for processing.
     */
    marshalled?: boolean;
    /**
     * A flag indicating whether the order contains data.
     */
    haveData?: boolean;
}
export namespace Order {
}


