/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A currency pair representing the exchange rate between two currencies.
 */
export const Pair = {
    EurPln: 'EUR_PLN',
    UsdPln: 'USD_PLN',
    ChfPln: 'CHF_PLN',
    GbpPln: 'GBP_PLN',
    EurUsd: 'EUR_USD',
    EurChf: 'EUR_CHF',
    EurGbp: 'EUR_GBP',
    GbpUsd: 'GBP_USD',
    UsdChf: 'USD_CHF',
    GbpChf: 'GBP_CHF'
} as const;
export type Pair = typeof Pair[keyof typeof Pair];

