/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessagePriority } from './messagePriority';


export interface SystemMessage { 
    messageText?: string;
    priority?: MessagePriority;
    id?: string;
    active?: boolean;
    /**
     * Record version
     */
    version?: number;
    dateFromUtc?: string;
    dateToUtc?: string;
}
export namespace SystemMessage {
}


