/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserTicketStatus } from './userTicketStatus';
import { EventType } from './eventType';
import { Direction } from './direction';
import { Pair } from './pair';


export interface UserTicket { 
    /**
     * A unique identifier for the user ticket, represented as a 64-bit integer.
     */
    id: number;
    /**
     * The monetary value associated with the user ticket, represented as a 64-bit integer.
     */
    amount: number;
    /**
     * The exchange ratio for the user ticket, represented as a 64-bit integer.
     */
    ratio: number;
    /**
     * A unique identifier for the user associated with the ticket, represented as a UUID.
     */
    userId?: string;
    /**
     * A unique identifier for the user account associated with the ticket, represented as a UUID.
     */
    userAccountId?: string;
    /**
     * The currency pair associated with the user ticket
     */
    pair: Pair;
    epochUtc: number;
    direction: Direction;
    eventType?: EventType;
    ticketStatus: UserTicketStatus;
    updatedDateUtc?: number;
    /**
     * Record version
     */
    version: number;
}
export namespace UserTicket {
}


