/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventType } from './eventType';
import { Currency } from './currency';


export interface UserOperation { 
    userId?: string;
    /**
     * A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
     */
    currency?: Currency;
    amount?: number;
    dateUtc?: string;
    eventType?: EventType;
}
export namespace UserOperation {
}


