/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface UserAccount { 
    /**
     * A unique identifier for the user account, represented as a UUID.
     */
    id?: string;
    /**
     * The currency used in the user account.
     */
    currency: Currency;
    /**
     * Record version
     */
    version: number;
}
export namespace UserAccount {
}


