/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    userName?: string;
    name?: string;
    email?: string;
    lastName?: string;
    blocked?: boolean;
    /**
     * Record version
     */
    version?: number;
}

