/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserBankAccount { 
    /**
     * user bank account id
     */
    id?: string;
    /**
     * user account id
     */
    userAccountId: string;
    /**
     * Country code in format ISO 3166-2
     */
    countryCode: string;
    accountNumber: string;
    /**
     * Date and time when the operation was created, in UTC timezone
     */
    createdDateUtc: string;
    /**
     * Date and time when the operation was verified, in UTC timezone
     */
    verifiedDateUtc?: string;
    /**
     * Record version
     */
    version: number;
}

