/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the user ticket.
 */
export const UserTicketStatus = {
    New: 'NEW',
    Active: 'ACTIVE',
    PartialRealized: 'PARTIAL_REALIZED',
    Realized: 'REALIZED',
    Cancelled: 'CANCELLED',
    PartialCanceled: 'PARTIAL_CANCELED'
} as const;
export type UserTicketStatus = typeof UserTicketStatus[keyof typeof UserTicketStatus];

