/**
 * Exchange App
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface UserAccountOperation { 
    userId?: string;
    amount: number;
    userAccountId: string;
    currency: Currency;
}
export namespace UserAccountOperation {
}


