openapi: "3.1.1"
info:
  title: Exchange App
  description: This is a REST API for the Exchange System application, which facilitates currency exchange operations.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
  - url: http://localhost:8080/
components:
  schemas:
    Pair:
      type: string
      description: A currency pair representing the exchange rate between two currencies.
      enum:
        - EUR_PLN
        - USD_PLN
        - CHF_PLN
        - GBP_PLN
        - EUR_USD
        - EUR_CHF
        - EUR_GBP
        - GBP_USD
        - USD_CHF
        - GBP_CHF

    Currency:
      type: string
      description: A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
      enum:
        - EUR
        - USD
        - GBP
        - CHF
        - PLN

    Direction:
      type: string
      description: Indicates the direction of the transaction, either selling or buying currency.
      enum:
        - SELL
        - BUY

    EventType:
      type: string
      description: The type of event associated with a transaction, such as deposit, withdrawal, or exchange.
      enum:
        - DEPOSIT
        - WITHDRAW
        - ORDER
        - EXCHANGE
        - CORRECTION
        - FEE
        - CANCEL

    Order:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - value
      properties:
        id:
          description: A unique identifier for the order, represented as a UUID.
          type: string
          format: uuid
        pair:
          description: The currency pair associated with the order.
          $ref: '#/components/schemas/Pair'
        amount:
          description: The monetary value of the order, represented as a 64-bit integer.
          type: integer
          format: int64
        direction:
          description: The direction of the order (buy or sell).
          $ref: '#/components/schemas/Direction'
        ratio:
          description: The exchange ratio for the order, represented as a 64-bit integer.
          type: integer
          format: int64
        event:
          description: An optional field to specify the event type related to the order.
          type: string
        ip:
          description: The IP address of the user making the order.
          type: string
        user:
          description: The identifier of the user who placed the order.
          type: string
        hash:
          description: A hash value for the order, represented as a 64-bit integer.
          type: integer
          format: int64
        journal:
          description: A flag indicating whether the order is logged in the journal.
          type: boolean
        checkedFinance:
          description: A flag indicating whether the financial aspects of the order have been checked.
          type: boolean
        marshalled:
          description: A flag indicating whether the order data has been marshalled for processing.
          type: boolean
        haveData:
          description: A flag indicating whether the order contains data.
          type: boolean

    UserAccount:
      type: object
      required:
        - currency
        - version
      properties:
        id:
          description: A unique identifier for the user account, represented as a UUID.
          type: string
          format: uuid
        currency:
          description: The currency used in the user account.
          $ref: '#/components/schemas/Currency'
        version:
          description: Record version
          type: integer
          format: int32

    UserTicket:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - amount
        - epochUtc
        - version
        - ticketStatus
      properties:
        id:
          description: A unique identifier for the user ticket, represented as a 64-bit integer.
          type: integer
          format: int64
        amount:
          description: The monetary value associated with the user ticket, represented as a 64-bit integer.
          type: integer
          format: int64
        ratio:
          description: The exchange ratio for the user ticket, represented as a 64-bit integer.
          type: integer
          format: int64
        userId:
          description: A unique identifier for the user associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        userAccountId:
          description: A unique identifier for the user account associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        pair:
          description: The currency pair associated with the user ticket
          $ref: '#/components/schemas/Pair'
        epochUtc:
          type: integer
          format: int64
        direction:
          description: The direction of the order (buy or sell).
          $ref: '#/components/schemas/Direction'
        eventType:
          $ref: '#/components/schemas/EventType'
        ticketStatus:
          $ref: '#/components/schemas/UserTicketStatus'
        updatedDateUtc:
          description: Date and time when the ticket was updated, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: integer
          format: int64
        version:
          description: Record version
          type: integer
          format: int32
    UserOperation:
      type: object
      properties:
        userId:
          description: A unique identifier for the user represented as a UUID.
          type: string
          format: uuid
        currency:
          $ref: '#/components/schemas/Currency'
          description: A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
        amount:
          description: The monetary value associated with the operation, represented as a 64-bit integer.
          type: integer
          format: int64
        dateUtc:
          description: Date and time when the operation was registered, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: string
          format: date-time
        eventType:
          $ref: '#/components/schemas/EventType'
    
    ErrorObjectResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: A code representing the type of error
        errorId:
          type: string
          format: uuid
          description: A unique identifier for the error instance
        message:
          type: string
          description: A descriptive message explaining the error
        timestampUtc:
          type: string
          format: date-time
          description: The timestamp when the error occurred, recorded in UTC timezone

    User:
      type: object
      properties:
        userName:
          type: string
        name:
          type: string
        email:
          type: string
        lastName:
          type: string
        blocked:
          type: boolean
        version:
          description: Record version
          type: integer
          format: int32
    UserTicketStatus:
      type: string
      description: The status of the user ticket.
      enum:
        - NEW
        - ACTIVE
        - PARTIAL_REALIZED
        - REALIZED
        - CANCELLED
        - PARTIAL_CANCELED
    OrderBookRow:
      type: object
      required:
        - r
        - a
      properties:
        r:
          description: ratio of currency
          type: integer
          format: int64
        a:
          description: amount of currency
          type: integer
          format: int64
    OrderBookData:
      type: object
      required:
        - b
        - s
      properties:
        p:
          description: pair
          $ref: '#/components/schemas/Pair'
        f:
          description: is full order book or partial
          type: boolean
        b:
          description: buy order book
          type: array
          items:
            $ref: '#/components/schemas/OrderBookRow'
        s:
          description: sell order book
          type: array
          items:
            $ref: '#/components/schemas/OrderBookRow'
    UserAccountOperation:
      type: object
      required:
        - currency
        - amount
        - userAccountId
      properties:
        userId:
          description: A unique identifier for the user represented as a UUID.
          type: string
          format: uuid
        amount:
          description: The monetary value associated with the operation, represented as a 64-bit integer.
          type: integer
          format: int64
        userAccountId:
          description: A unique identifier for the user account associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        currency:
          $ref: '#/components/schemas/Currency'
    ExchangeEvent:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - dateUtc
        - amount
        - amountRealized
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the exchange event
        pair:
          $ref: '#/components/schemas/Pair'
          description: Trading pair associated with the exchange event
        amount:
          type: integer
          format: int64
          description: Value involved in the exchange event
        amountRealized:
          type: integer
          format: int64
          description: Value exchanged in the exchange event.For full exchange value is equal to 'amount' field;
        direction:
          $ref: '#/components/schemas/Direction'
          description: Direction of the exchange event (buy/sell)
        ratio:
          type: integer
          format: int64
          description: Ratio for the exchange event
        dateUtc:
          description: Date and time when the exchange occurred, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: string
          format: date-time
    UserBankAccount:
      type: object
      required:
        - userAccountId
        - version
        - countryCode
        - accountNumber
        - createdDateUtc
      properties:
        id:
          description: user bank account id
          type: string
          format: uuid
        userAccountId:
          description: A unique identifier for the user account associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        countryCode:
          description: Country code in format ISO 3166-2
          type: string
        accountNumber:
          description: Bank account number, different for different countries, no validation
          type: string
        createdDateUtc:
          description: Date and time when the operation was created, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: string
          format: date-time
        verifiedDateUtc:
          description: Date and time when the operation was verified, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: string
          format: date-time
        version:
          description: Record version
          type: integer
          format: int32
