openapi: "3.1.1"
info:
  title: Exchange Admin App Actuator
  description: "This is a REST API for the Admin Exchange System application, built using Spring Boot Actuator. It facilitates internal monitoring and management of the application."
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/"
    description: "The server hosting the Admin Exchange System Actuator. Typically used for local development."
paths:
  /actuator/health:
    get:
      summary: "Health Check"
      description: "Endpoint to check the health status of the application. This provides insights into the availability and responsiveness of the system."
      operationId: loadActuatorInternalHealthCheck
      x-application-role: "hasAuthority('ADMIN')"
      tags:
        - actuator-internal
      responses:
        '200':
          description: "Indicates that the application is healthy and responsive. This response includes status details in JSON format."
          content:
            application/json:
              schema:
                type: object
                description: "JSON object representing the health status, including any relevant details."
