openapi: "3.1.1"
info:
  title: Exchange App
  description: This is a REST API for the Exchange System application, which facilitates currency exchange operations.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
  - url: http://localhost:8080/
paths:
  /users/property:
    get:
      summary: Get user property
      operationId: getUserProperty
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      tags:
        - users
      responses:
        '200':
          description: user account object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProperty"
        '404':
          description: user account not found
        '403':
          description: Unauthorized request
    post:
      summary: Save user property
      operationId: saveUserProperty
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      requestBody:
        description: user property object to save
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProperty"
      tags:
        - users
      responses:
        '200':
          description: user property created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProperty"
        '404':
          description: user account not found
        '403':
          description: Unauthorized request
  /users/address:
    get:
      summary: Get user address data
      operationId: getUserAddress
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      tags:
        - users
      responses:
        '200':
          description: user address object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        '404':
          description: user address not found
        '403':
          description: Unauthorized request
    post:
      summary: Save user address
      operationId: saveUserAddress
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      requestBody:
        description: user address object to save
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
      tags:
        - users
      responses:
        '200':
          description: user address created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        '404':
          description: user account not found
        '403':
          description: Unauthorized request
components:
  schemas:
    UserAccountRequest:
      type: object
      properties:
        userId:
          description: "A unique identifier for the user, represented as a UUID."
          type: string
          format: uuid

    UserProperty:
      type: object
      required:
        - language
        - timezone
        - version
      properties:
        language:
          type: string
          description: "The preferred language of the user, typically represented in ISO 639 format."
        locale:
          type: string
          description: "The locale setting defining language and regional preferences, such as 'en-US'."
        timezone:
          type: string
          description: "The timezone where the user is located, following the IANA time zone database format."
        userId:
          description: "A unique identifier for the user, represented as a UUID."
          type: string
          format: uuid
        version:
          description: "Record version for tracking changes to user properties."
          type: integer
          format: int32

    UserData:
      type: object
      properties:
        name:
          type: string
          description: "The full name of the user."
        email:
          type: string
          description: "The email address associated with the user account, used for communication and notifications."
        userId:
          description: "A unique identifier for the user, represented as a UUID."
          type: string
          format: uuid

    UserStatus:
      type: string
      description: "The current status of the user account, indicating whether the account is active or disabled."
      enum:
        - ACTIVE
        - DISABLED

    Address:
      type: object
      required:
        - name
        - version
        - countryCode
      properties:
        id:
          type: string
          format: uuid
          description: "A unique identifier for the address entry, represented as a UUID."
        userId:
          description: "A unique identifier for the user, represented as a UUID."
          type: string
          format: uuid
        name:
          type: string
          description: "The name associated with the address, often the recipient's name."
        countryCode:
          description: "Country code formatted according to ISO 3166-2 standards, representing the country of the address."
          type: string
        street:
          type: string
          description: "The street address, including street number and name."
        zipCode:
          type: string
          description: "The postal code for the address, used for mail delivery."
        city:
          type: string
          description: "The city of the address."
        taxID:
          type: string
          description: "The tax identification number for the user, used for tax purposes."
        vatID:
          type: string
          description: "The VAT identification number for transactions subject to value-added tax."
        phone:
          description: "Phone number for the user, used for communication."
          type: string
        version:
          description: "Record version for tracking changes to the address."
          type: integer
          format: int32
