openapi: "3.1.1"
info:
  title: Exchange App
  description: This is a REST API for the Exchange System application, which facilitates currency exchange operations.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
  - url: http://localhost:8080/
paths:
  /users/property:
    get:
      summary: Get user property
      operationId: getUserProperty
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      tags:
        - users
      responses:
        '200':
          description: user account object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProperty"
        '404':
          description: user account not found
        '403':
          description: Unauthorized request
    post:
      summary: Save user property
      operationId: saveUserProperty
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      requestBody:
        description: user property object to save
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProperty"
      tags:
        - users
      responses:
        '200':
          description: user property created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProperty"
        '404':
          description: user account not found
        '403':
          description: Unauthorized request
  /users/address:
    get:
      summary: Get user address data
      operationId: getUserAddress
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      tags:
        - users
      responses:
        '200':
          description: user address object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        '404':
          description: user address not found
        '403':
          description: Unauthorized request
    post:
      summary: Save user address
      operationId: saveUserAddress
      x-application-role: hasAuthority('ADMIN') or hasAuthority('USER')
      requestBody:
        description: user address object to save
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Address"
      tags:
        - users
      responses:
        '200':
          description: user address created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        '404':
          description: user account not found
        '403':
          description: Unauthorized request
components:
  schemas:
    UserAccountRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
    UserProperty:
      type: object
      required:
        - language
        - timezone
        - version
      properties:
        language:
          type: string
        locale:
          type: string
        timezone:
          type: string
        userId:
          type: string
          format: uuid
        version:
          description: Record version
          type: integer
          format: int32
    UserData:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        userId:
          type: string
          format: uuid
    UserStatus:
      type: string
      description: A status of the User.
      enum:
        - ACTIVE
        - DISABLED
    Address:
      type: object
      required:
        - name
        - version
        - countryCode
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        name:
          type: string
        countryCode:
          description: Country code in format ISO 3166-2
          type: string
        street:
          type: string
        zipCode:
          type: string
        city:
          type: string
        taxID:
          type: string
        vatID:
          type: string
        phone:
          type: string
        version:
          description: Record version
          type: integer
          format: int32