openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for the Exchange System application, which facilitates currency exchange operations.
  version: 1.0.0
paths:
  /users/property:
    get:
      summary: Get user property
      operationId: getUserProperty
      tags:
        - users
      responses:
        '200':
          description: user account object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProperty"
        '404':
          description: user account not found
        '403':
          description: unauthorized request
    post:
      summary: Save user property
      operationId: saveUserProperty
      requestBody:
        description: user property object to save
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProperty"
      tags:
        - users
      responses:
        '201':
          description: user property created
        '404':
          description: user account not found
        '403':
          description: unauthorized request
components:
  schemas:
    UserAccountRequest:
      type: object
      properties:
        userId:
          type: string
          format: UUID
    UserProperty:
      type: object
      required:
        - language
        - timezone
        - version
      properties:
        language:
          type: string
        timezone:
          type: string
        userId:
          type: string
          format: uuid
        version:
          description: Record version
          type: integer
          format: int32
    UserData:
      type: object
      properties:
        name:
          type: string
    UserStatus:
      type: string
      description: A status of the User.
      enum:
        - ACTIVE
        - DISABLED
