FROM amazoncorretto:25-jdk
WORKDIR /app

COPY target/backend-admin-*.jar /app/backend-admin.jar

ENTRYPOINT ["java", "-Xms128M", "-Xmx512M", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001", "-jar", "/app/backend-admin.jar"]