FROM openjdk:25-jdk-slim
WORKDIR /app

COPY target/backend-internal-*.jar /app/backend-internal.jar

ENTRYPOINT ["java", "-Xms128M", "-Xmx512M", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000", "-jar", "/app/backend-internal.jar"]