openapi: "3.1.1"
info:
  title: Exchange App
  description: This is a REST API for Exchange System application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /orders/book:
    get:
      summary: Retrieve all orders
      operationId: getOrderBook
      x-application-role: hasAuthority('ADMIN')
      tags:
        - orders
      responses:
        '200':
          description: A list of all orders in the system
          content:
            application/json:
              schema:
                type: array
                items:
                  type: Order
components:
  schemas:
    CancelOrder:
      type: object
      required:
        - orderId
        - cancelOrderId
        - pair
        - direction
      properties:
        orderId:
          type: string
          format: uuid
          description: Unique identifier for the order to be canceled
        cancelOrderId:
          type: string
          format: uuid
          description: Unique identifier for the cancellation order
        pair:
          type: Pair
          description: Trading pair associated with the order
        direction:
          type: Direction
          description: Direction of the order (buy/sell)

    OrderTicket:
      type: object
      required:
        - id
        - amount
        - userId
        - currency
        - ratio
        - ticketDateUtc
        - pair
        - direction
        - finishOrder
        - flagSaved
        - flagCancelled
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the order ticket
        userId:
          type: string
          format: uuid
          description: Unique identifier for the user who created the order
        pair:
          type: Pair
          description: Trading pair associated with the order
        direction:
          type: Direction
          description: Direction of the order (buy/sell)
        ticketDateUtc:
          description: Date and time when the order was created, in UTC timezone
          type: string
          format: date-time
        ratio:
          type: integer
          format: int64
          description: Ratio for the order
        amount:
          type: integer
          format: int64
          description: Amount of currency involved in the order
        finishOrder:
          type: boolean
          default: false
          description: Indicates whether the order is finished
        currency:
          type: Currency
          description: Identifier for the currency used in the order
        flagSaved:
          type: boolean
          default: false
          description: Indicates whether the order ticket is saved
        flagCancelled:
          type: boolean
          default: false
          description: Indicates whether the order ticket is canceled

    ExchangeTicket:
      allOf:
        - $ref: "#/components/schemas/OrderTicket"
        - type: object
          properties:
            reverseOrderId:
              type: integer
              format: int64
              description: Unique identifier for the reverse order
            exchangeDateUtc:
              description: Date and time when the exchange occurred, in UTC timezone
              type: string
              format: date-time

