openapi: "3.1.1"
info:
  title: Exchange Admin App Errors API
  description: This is a REST API for Admin Exchange System application for Errors Management.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /errors/list:
    post:
      summary: Load Error List
      operationId: loadErrorList
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: request params
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorListRequest'
      tags:
        - adminErrors
      responses:
        '200':
          description: Operation completed successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorMessage'
        '403':
          description: Unauthorized request
  /errors/{id}:
    delete:
      summary: Delete Error with specific ID
      operationId: deleteError
      x-application-role: hasAuthority('ADMIN')
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the error
      tags:
        - adminErrors
      responses:
        '204':
          description: Operation completed successfully
        '403':
          description: Unauthorized request
components:
  schemas:
    ErrorListRequest:
      type: object
      required:
        - offset
        - size
      properties:
        offset:
          type: integer
          format: int32
          minimum: 0
          description: >
            The starting point from which to retrieve error messages. This is 
            used for pagination and indicates the number of entries to skip 
            before starting to return results.
        size:
          type: integer
          format: int32
          minimum: 1
          description: >
            The maximum number of error messages to return in the response. 
            This allows the client to specify how many entries to fetch 
            at one time, facilitating pagination of the results.

    ErrorMessage:
      type: object
      required:
        - id
        - message
        - offset
        - timestamp
      properties:
        id:
          type: string
          description: >
            A unique identifier for the error message. This ID is used to 
            reference the specific error in logs or troubleshooting processes.
        message:
          type: string
          description: >
            A descriptive message providing details about the error that occurred. 
            This should inform the user or the developer about what went wrong.
        timestamp:
          type: integer
          format: int64
          description: >
            The Unix timestamp indicating when the error occurred, measured in 
            milliseconds since epoch. This is useful for tracking when issues arise 
            in the application.
        offset:
          type: integer
          format: int64
          minimum: 0
          description: >
            A numeric value indicating the offset position of the error message in 
            the log or messages list. This can help in determining the sequence 
            of errors and their relationships.