openapi: "3.1.1"
info:
  title: Exchange Admin App Accounts API
  description: This is a REST API for Admin Exchange System application for Accounts Management.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /accounts/deposit:
    post:
      summary: Save Deposit for User Account
      operationId: saveAccountDeposit
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: New deposit data to be added to the user account.
        required: true
        content:
          application/json:
            schema:
              type: UserAccountOperation
      tags:
        - adminAccounts
      responses:
        '204':
          description: Operation completed successfully.
        '404':
          description: Error - user or account not found.
        '403':
          description: Unauthorized request.

  /accounts/withdraw:
    post:
      summary: Save Exchange Ticket
      operationId: saveWithdrawRequest
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: New exchange ticket object representing the withdrawal request.
        required: true
        content:
          application/json:
            schema:
              type: UserAccountOperation
      tags:
        - adminAccounts
      responses:
        '204':
          description: Operation completed successfully.
        '404':
          description: Error - user or account not found.
        '400':
          description: Returned when a user has insufficient funds for a money operation or incorrect Withdraw amount.
        '403':
          description: Unauthorized request.

  /accounts/list:
    post:
      summary: User Account List
      operationId: loadAccounts
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: Search parameters for retrieving user accounts.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAccountRequest"
      tags:
        - adminAccounts
      responses:
        '200':
          description: List of user accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserAccount
        '404':
          description: Error - user or account not found.
        '403':
          description: Unauthorized request.

  /accounts/system/list:
    get:
      summary: System Account List
      operationId: loadSystemAccountList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      responses:
        '200':
          description: List of system user accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserAccount
        '403':
          description: Unauthorized request.

  /accounts/exchange/list:
    get:
      summary: Exchange Account List
      operationId: loadExchangeAccountList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      responses:
        '200':
          description: List of exchange user accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserAccount
        '403':
          description: Unauthorized request.

  /accounts/amount:
    post:
      summary: Get current amount on account
      operationId: loadAccountAmount
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: Search parameters to retrieve the current account amount.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountAmountRequest"
      responses:
        '200':
          description: Current amount on the specified account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAmountResponse'

  /accounts/operations:
    post:
      summary: Account Operation List
      operationId: loadAccountOperationList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: Search parameters for retrieving account operations.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountOperationsRequest"
      responses:
        '200':
          description: List of account operations performed on the system.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountOperation'
        '404':
          description: Account not found.
        '403':
          description: Unauthorized request.

  /accounts/bank:
    post:
      summary: Bank Account List for the User
      operationId: loadBankAccountList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: Search parameters to retrieve the user's bank accounts.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserBankAccountRequest"
      responses:
        '200':
          description: List of bank accounts associated with the user.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserBankAccount
        '404':
          description: Account not found.
        '403':
          description: Unauthorized request.

  /accounts/bank/validate:
    post:
      summary: Validate Bank Account
      operationId: validateBankAccount
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: Bank account details to be validated.
        required: true
        content:
          application/json:
            schema:
              type: UserBankAccount
      responses:
        '204':
          description: Bank account is validated successfully.
        '404':
          description: Account not found.
        '403':
          description: Unauthorized request.
        '409':
          description: Conflict when the version of the bank account is incorrect.
  /accounts/withdraw/limit:
    get:
      summary: Load Minimal Withdraw Limit List for Currencies
      operationId: loadWithdrawLimitList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      responses:
        '200':
          description: Withdraw List
          content:
            application/json:
              schema:
                type: array
                items:
                  type: Withdraw
        '403':
          description: Unauthorized request
components:
  schemas:
    UserAccountRequest:
      type: object
      properties:
        userId:
          description: A unique identifier for the user represented as a UUID.
          type: string
          format: uuid

    AccountOperationsRequest:
      type: object
      required:
        - systemAccountId
        - dateFromUtc
      properties:
        dateFromUtc:
          type: string
          format: date
          description: The start date for the query, expressed in UTC format (YYYY-MM-DD).
        dateToUtc:
          type: string
          format: date
          description: The end date for the query, expressed in UTC format (YYYY-MM-DD).
        systemAccountId:
          description: System account ID for which the operations are to be fetched.
          type: string
          format: uuid

    AccountAmountRequest:
      type: object
      required:
        - accountId
      properties:
        accountId:
          description: Unique identifier for the account represented as a UUID.
          type: string
          format: uuid

    AccountAmountResponse:
      type: object
      properties:
        amount:
          description: >
            Total monetary balance for the specified currency.
            Represented as a 64-bit integer to ensure precise financial calculations 
            and avoid floating-point precision issues.
            
            Monetary Value Representation:
            - 1 cent = 100 amount units
            - For USD: 
              * $10.25 would be represented as 102500 amount units
              * $0.50 would be represented as 5000 amount units
            
            This approach provides:
            - High precision for financial calculations
            - Elimination of floating-point rounding errors
            - Consistent representation across different currencies
          type: integer
          format: int64

    AccountOperation:
      type: object
      required:
        - amount
        - currency
        - dateUtc
      properties:
        dateUtc:
          description: Date and time when the operation was created, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: string
          format: date-time
        amount:
          description: >
            Total monetary balance for the specified currency.
            Represented as a 64-bit integer to ensure precise financial calculations 
            and avoid floating-point precision issues.

            Monetary Value Representation:
            - 1 cent = 100 amount units
            - For USD: 
              * $10.25 would be represented as 102500 amount units
              * $0.50 would be represented as 5000 amount units

            This approach provides:
            - High precision for financial calculations
            - Elimination of floating-point rounding errors
            - Consistent representation across different currencies
          type: integer
          format: int64
        currency:
          type: Currency
          description: A currency code representing the type of currency used in transactions. The codes follow the ISO 4217 standard, assigning a three-digit numeric code to each currency.
        eventType:
          type: EventType

    UserBankAccountRequest:
      type: object
      required:
        - userAccountId
        - userId
      properties:
        userAccountId:
          description: A unique identifier for the user account associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        userId:
          description: A unique identifier for the user represented as a UUID.
          type: string
          format: uuid