openapi: "3.1.1"
info:
  title: Exchange Admin App Accounts API
  description: This is a REST API for Admin Exchange System application for Accounts Management.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /accounts/deposit:
    post:
      summary: Save Deposit for User Account
      operationId: saveAccountDeposit
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: new deposit data
        required: true
        content:
          application/json:
            schema:
              type: UserAccountOperation
      tags:
        - adminAccounts
      responses:
        '204':
          description: Operation completed successfully
        '404':
          description: Error user or account not found.
        '403':
          description: Unauthorized request
  /accounts/withdraw:
    post:
      summary: Save Exchange Ticket
      operationId: saveWithdrawRequest
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: new exchange ticket object
        required: true
        content:
          application/json:
            schema:
              type: UserAccountOperation
      tags:
        - adminAccounts
      responses:
        '204':
          description: Operation completed successfully
        '404':
          description: Error user or account not found.
        '400':
          description: Returned when a user has insufficient funds for a money operation.
        '403':
          description: Unauthorized request
  /accounts/list:
    post:
      summary: User Account List
      operationId: loadAccounts
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAccountRequest"
      tags:
        - adminAccounts
      responses:
        '200':
          description: List of user accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserAccount
        '404':
          description: Error user or account not found.
        '403':
          description: Unauthorized request
  /accounts/system/list:
    get:
      summary: System Account List
      operationId: loadSystemAccountList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      responses:
        '200':
          description: List of user accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserAccount
        '403':
          description: Unauthorized request
  /accounts/exchange/list:
    get:
      summary: Exchange Account List
      operationId: loadExchangeAccountList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      responses:
        '200':
          description: List of user accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserAccount
        '403':
          description: Unauthorized request
  /accounts/amount:
    post:
      summary: Get current amount on account
      operationId: loadAccountAmount
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountAmountRequest"
      responses:
        '200':
          description: List of system account operations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAmountResponse'
  /accounts/operations:
    post:
      summary: Account Operation List
      operationId: loadAccountOperationList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountOperationsRequest"
      responses:
        '200':
          description: List of system account operations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountOperation'
        '404':
          description: Account not found
        '403':
          description: Unauthorized request
  /accounts/bank:
    post:
      summary: Bank Account List for the User
      operationId: loadBankAccountList
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserBankAccountRequest"
      responses:
        '200':
          description: List of system account operations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserBankAccount
        '404':
          description: Account not found
        '403':
          description: Unauthorized request
  /accounts/bank/validate:
    post:
      summary: Validate Bank Account
      operationId: validateBankAccount
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminAccounts
      requestBody:
        description: bank account to be validated
        required: true
        content:
          application/json:
            schema:
              type: UserBankAccount
      responses:
        '204':
          description: bank account is validated
        '404':
          description: Account not found
        '403':
          description: Unauthorized request
        '409':
          description: Conflict when wrong version
components:
  schemas:
    UserAccountRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
    AccountOperationsRequest:
      type: object
      required:
        - systemAccountId
        - dateFromUtc
      properties:
        dateFromUtc:
          type: string
          format: date
        dateToUtc:
          type: string
          format: date
        systemAccountId:
          description: System account Id
          type: string
          format: uuid
    AccountAmountRequest:
      type: object
      required:
        - accountId
      properties:
        accountId:
          description: Account Id
          type: string
          format: uuid
    AccountAmountResponse:
      type: object
      properties:
        amount:
          description: The monetary value of the order, represented as a 64-bit integer.
          type: integer
          format: int64
    AccountOperation:
      type: object
      required:
        - amount
        - currency
        - dateUtc
      properties:
        dateUtc:
          description: Date and time when the operation was created, in UTC timezone
          type: string
          format: date-time
        amount:
          description: The monetary value associated with the operation, represented as a 64-bit integer.
          type: integer
          format: int64
        currency:
          type: string
        eventType:
          type: EventType
    UserBankAccountRequest:
      type: object
      required:
        - userAccountId
        - userId
      properties:
        userAccountId:
          description: Account Id
          type: string
          format: uuid
        userId:
          type: string
          format: uuid