openapi: "3.1.1"
info:
  title: Exchange Admin App Properties API
  description: This is a REST API for Admin Exchange System application for Reports.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /properties/system:
    get:
      summary: Load System Properties
      operationId: loadSystemProperties
      tags:
        - adminProperties
      responses:
        '200':
          description: System properties loaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemPropertyResponse'
components:
  schemas:
    SystemPropertyResponse:
      type: object
      required:
        - ratioStrategy
        - feeStrategy
      properties:
        ratioStrategy:
          type: string
        feeStrategy:
          type: string