openapi: "3.1.1"
info:
  title: Exchange Admin App Transactions API
  description: This is a REST API for Admin Exchange System application for Transactions Management.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /transactions/list:
    post:
      summary: List transactions
      operationId: loadTransactionList
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /transactions/system/list:
    post:
      summary: List transactions on system accounts
      operationId: loadSystemAccountTransactionList
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /transactions/exchange/list:
    post:
      summary: List fee transactions
      operationId: loadExchangeAccountTransactionList
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /transactions/correction:
    post:
      summary: Save Correction operation
      operationId: saveCorrectionRequest
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: new exchange ticket object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CorrectionRequest"
      tags:
        - adminTransactions
      responses:
        '204':
          description: Operation completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CorrectionId"
        '404':
          description: Error account not found.
        '403':
          description: Unauthorized request
  /transactions/user/list:
    post:
      summary: List fee transactions
      operationId: loadUserTransactionList
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectUserTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
components:
  schemas:
    SelectTransactionRequest:
      type: object
      properties:
        dateFromUtc:
          type: string
          format: date-time
          description: The start date and time for the query, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
        dateToUtc:
          type: string
          format: date-time
          description: The end date and time for the query, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
    Transaction:
      type: object
      required:
        - userId
      properties:
        dateUtc:
          description: Date and time when the transaction was created, in UTC timezone, expressed in UTC format (YYYY-MM-DDTHH:mm:ssZ).
          type: string
          format: date-time
        amount:
          description: >
            Total monetary balance for the specified currency.
            Represented as a 64-bit integer to ensure precise financial calculations 
            and avoid floating-point precision issues.

            Monetary Value Representation:
            - 1 cent = 100 amount units
            - For USD: 
              * $10.25 would be represented as 102500 amount units
              * $0.50 would be represented as 5000 amount units

            This approach provides:
            - High precision for financial calculations
            - Elimination of floating-point rounding errors
            - Consistent representation across different currencies
          type: integer
          format: int64
        currency:
          type: Currency
          description: A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
    CorrectionRequest:
      type: object
      required:
        - userAccountId
        - amount
      properties:
        userAccountId:
          description: A unique identifier for the user account associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        amount:
          description: >
            Total monetary balance for the specified currency.
            Represented as a 64-bit integer to ensure precise financial calculations 
            and avoid floating-point precision issues.

            Monetary Value Representation:
            - 1 cent = 100 amount units
            - For USD: 
              * $10.25 would be represented as 102500 amount units
              * $0.50 would be represented as 5000 amount units

            This approach provides:
            - High precision for financial calculations
            - Elimination of floating-point rounding errors
            - Consistent representation across different currencies
          type: integer
          format: int64
        userId:
          description: A unique identifier for the user represented as a UUID.
          type: string
          format: uuid
    CorrectionId:
      type: object
      required:
        - id
      properties:
        id:
          description: A unique identifier for the user transaction, represented as a 64-bit integer.
          type: integer
          format: int64
    SelectUserTransactionRequest:
      type: object
      required:
        - userAccountId
        - userId
      properties:
        userId:
          description: A unique identifier for the user associated with the ticket, represented as a UUID.
          type: string
          format: uuid
        userAccountId:
          description: A unique identifier for the user account associated with the ticket, represented as a UUID.
          type: string
          format: uuid
