openapi: "3.1.1"
info:
  title: Exchange Admin App Reports API
  description: This is a REST API for Admin Exchange System application for Reports.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /reports/accounts:
    post:
      summary: User Account List
      operationId: generateAccountsReport
      x-application-role: hasAuthority('ADMIN')
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountsReportRequest"
      tags:
        - adminReports
      responses:
        '200':
          description: Report of user accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountsReportResponse'
  /reports/operations-pdf:
    post:
      summary: Returns the Operations Report in the PDF format
      operationId: loadOperationPdfDocument
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminReports
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountOperationsRequest'
      responses:
        '200':
          description: A PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Exchange ticket not found
        '403':
          description: Authorization information is missing or invalid.
components:
  schemas:
    AccountsReportRequest:
      type: object
      required:
        - userId
        - dateFromUtc
      properties:
        userId:
          description: A unique identifier for the user represented as a UUID.
          type: string
          format: uuid
        dateFromUtc:
          type: string
          format: date-time
        dateToUtc:
          type: string
          format: date-time
    AccountsReportResponse:
      type: object
      properties:
        reportDateUtc:
          description: Date and time when the report was created, in UTC timezone
          type: string
          format: date-time
        amountDeposits:
          type: integer
          format: int64
        amountWithdraws:
          type: integer
          format: int64
        amountExchanges:
          type: integer
          format: int64
        amountFees:
          type: integer
          format: int64
        amountCorrections:
          type: integer
          format: int64
        amountCancellations:
          type: integer
          format: int64
        currency:
          type: Currency
          description: A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
    AccountOperationsRequest:
      type: object
      required:
        - systemAccountId
        - dateFromUtc
      properties:
        dateFromUtc:
          type: string
          format: date
        dateToUtc:
          type: string
          format: date
        systemAccountId:
          description: System account Id
          type: string
          format: uuid