openapi: "3.1.1"
info:
  title: Exchange Admin App Transactions API
  description: This is a REST API for Admin Exchange System application for Transactions Management.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /transactions/list:
    post:
      summary: List transactions
      operationId: loadTransactionList
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /transactions/system/list:
    post:
      summary: List transactions on system accounts
      operationId: loadSystemAccountTransactionList
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /transactions/exchange/list:
    post:
      summary: List fee transactions
      operationId: loadExchangeAccountTransactionList
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectTransactionRequest"
      tags:
        - adminTransactions
      responses:
        '200':
          description: List of Transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
components:
  schemas:
    SelectTransactionRequest:
      type: object
      properties:
        dateFromUtc:
          type: string
          format: date-time
        dateToUtc:
          type: string
          format: date-time
    Transaction:
      type: object
      required:
        - userId
      properties:
        dateUtc:
          type: string
          format: date-time
        amount:
          type: integer
          format: int64
