openapi: "3.1.0"
info:
  title: Exchange Admin App Actuator
  description: This is a REST API for Admin Exchange System application for SpringBoot Actuator Admin Backend.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /actuator/health:
    get:
      summary: Health Check
      operationId: loadActuatorAdminHealthCheck
      tags:
        - actuator-admin
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
