openapi: "3.1.1"
info:
  title: Exchange Admin App Statistics API
  description: This is a REST API for Admin Exchange System application for System Statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /statistics/users:
    post:
      summary: Load user statistics
      operationId: loadUsersStatistic
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminStatistics
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsersStatisticRequest"
      responses:
        '200':
          description: User status updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersStatisticResponse"
  /statistics/pair/{pair}:
    get:
      summary: Load pair statistics
      operationId: loadPairStatistics
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminStatistics
      parameters:
        - in: path
          name: pair
          schema:
            type: Pair
          required: true
          description: Pair parameter for statistics
      responses:
        '200':
          description: User status updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PairStatisticResponse"
        '404':
          description: statistics data not found
  /statistics/currency/{currency}:
    get:
      summary: Load currency statistics
      operationId: loadCurrencyStatistics
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminStatistics
      parameters:
        - in: path
          name: currency
          schema:
            type: string
          required: true
          description: currency parameter for statistics
      responses:
        '200':
          description: User status updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrencyStatisticResponse"
        '404':
          description: statistics data not found
components:
  schemas:
    UsersStatisticRequest:
      type: object
      required:
        - userId
        - currency
      properties:
        userId:
          type: string
          format: uuid
        currency:
          type: Currency
          description: A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency

    UsersStatisticResponse:
      type: object
      required:
        - allTickets
        - activeTickets
        - amountInTickets
        - amountTotal
      properties:
        allTickets:
          type: integer
          format: int32
        activeTickets:
          type: integer
          format: int32
        amountInTickets:
          type: integer
          format: int64
        amountTotal:
          type: integer
          format: int64
    PairStatisticResponse:
      type: object
      required:
        - amountTicketsSell
        - amountTicketsBuy
        - countTicketsSell
        - countTicketsBuy
      properties:
        amountTicketsSell:
          type: integer
          format: int64
        countTicketsSell:
          type: integer
          format: int32
        amountTicketsBuy:
          type: integer
          format: int64
        countTicketsBuy:
          type: integer
          format: int32

    CurrencyStatisticResponse:
      type: object
      required:
        - amountTotal
        - amountInTickets
        - currency
      properties:
        amountTotal:
          type: integer
          format: int64
        amountInTickets:
          type: integer
          format: int64
        currency:
          type: Currency
          description: A currency code representing the type of currency used in transactions.The codes follow the ISO 4217 standard a three-digit numeric code to each currency
