openapi: "3.1.1"
info:
  title: Exchange Admin App Statistics API
  description: This is a REST API for Admin Exchange System application for System Statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /statistics/users:
    post:
      summary: Load user statistics
      operationId: loadUsersStatistic
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminStatistics
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsersStatisticRequest"
      responses:
        '200':
          description: User status updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersStatisticResponse"
  /statistics/pair/{pair}:
    get:
      summary: Load pair statistics
      operationId: loadPairStatistics
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminStatistics
      parameters:
        - in: path
          name: pair
          schema:
            type: Pair
          required: true
          description: Pair parameter for statistics
      responses:
        '200':
          description: User status updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PairStatisticResponse"
        '404':
          description: statistics data not found
  /statistics/currency/{currency}:
    get:
      summary: Load currency statistics
      operationId: loadCurrencyStatistics
      x-application-role: hasAuthority('ADMIN')
      tags:
        - adminStatistics
      parameters:
        - in: path
          name: currency
          schema:
            type: string
          required: true
          description: currency parameter for statistics
      responses:
        '200':
          description: User status updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrencyStatisticResponse"
        '404':
          description: statistics data not found
components:
  schemas:
    UsersStatisticRequest:
      type: object
      required:
        - userId
        - currency
      properties:
        userId:
          type: string
          format: uuid
          description: >
            A unique identifier for the user, represented as a UUID (Universally 
            Unique Identifier). This ID is essential for accurately retrieving 
            the statistics related to the specified user.
        currency:
          type: Currency
          description: >
            A currency code representing the type of currency used in transactions. 
            The codes follow the ISO 4217 standard, assigning a three-digit 
            numeric code to each currency, ensuring clarity and consistency in 
            financial reporting.

    UsersStatisticResponse:
      type: object
      required:
        - allTickets
        - activeTickets
        - amountInTickets
        - amountTotal
      properties:
        allTickets:
          type: integer
          format: int32
          description: >
            The total number of tickets associated with the user, providing a 
            comprehensive view of user engagement or activity.
        activeTickets:
          type: integer
          format: int32
          description: >
            The number of currently active tickets held by the user. This 
            helps to assess the user's ongoing interactions or transactions.
        amountInTickets:
          type: integer
          format: int64
          description: >
            The total amount of funds represented in active tickets. This value 
            reflects the financial value the user has tied up in their active 
            tickets.
        amountTotal:
          type: integer
          format: int64
          description: >
            The overall amount of funds associated with all tickets (both 
            active and inactive), providing insight into the user's total 
            financial involvement.

    PairStatisticResponse:
      type: object
      required:
        - amountTicketsSell
        - amountTicketsBuy
        - countTicketsSell
        - countTicketsBuy
      properties:
        amountTicketsSell:
          type: integer
          format: int64
          description: >
            The total amount of funds represented by tickets sold. This metric 
            reflects the financial volume generated from selling tickets.
        countTicketsSell:
          type: integer
          format: int32
          description: >
            The total number of tickets sold during the reporting period. 
            This provides insight into the selling activity and user demand.
        amountTicketsBuy:
          type: integer
          format: int64
          description: >
            The total amount of funds represented by tickets bought. This metric 
            indicates the financial volume spent on purchasing tickets.
        countTicketsBuy:
          type: integer
          format: int32
          description: >
            The total number of tickets purchased during the reporting period. 
            This helps in assessing user buying activity and market trends.

    CurrencyStatisticResponse:
      type: object
      required:
        - amountTotal
        - amountInTickets
        - currency
      properties:
        amountTotal:
          type: integer
          format: int64
          description: >
            The total amount of funds in the specified currency, encompassing 
            all transactions. This figure is crucial for understanding overall 
            financial performance in that currency.
        amountInTickets:
          type: integer
          format: int64
          description: >
            The total amount of funds represented in tickets for the specified 
            currency. This shows how much value is currently tied to tickets 
            and can aid in financial forecasting.
        currency:
          type: Currency
          description: >
            A currency code representing the type of currency used in transactions. 
            The codes follow the ISO 4217 standard, which assigns a three-digit 
            numeric code to each currency, ensuring clarity and uniformity in 
            financial reporting.