openapi: "3.1.1"
info:
  title: Exchange Admin App Messages API
  description: This is a REST API for Admin Exchange System application for Reports.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /messages/message:
    post:
      summary: Block user in system
      operationId: saveSystemMessage
      tags:
        - adminMessages
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              type: SystemMessage
      responses:
        '201':
          description: Operation completed successfully
          content:
            application/json:
              schema:
                type: SystemMessage
    put:
      summary: Block user in system
      operationId: updateSystemMessage
      tags:
        - adminMessages
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              type: SystemMessage
      responses:
        '204':
          description: Operation completed successfully
        '404':
          description: object not found
  /messages/list:
    get:
      summary: Load System Message List
      operationId: loadSystemMessageList
      tags:
        - adminMessages
      responses:
        '200':
          description: Operation completed successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: SystemMessage