openapi: "3.1.0"
info:
  title: Exchange Admin App Reports API
  description: This is a REST API for Admin Exchange System application for Reports.
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /reports/accounts:
    post:
      summary: User Account List
      operationId: generateAccountsReport
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountsReportRequest"
      tags:
        - adminReports
      responses:
        '200':
          description: Report of user accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsReportResponse'
  /reports/system-operations-pdf:
    post:
      summary: Returns the System Operations Report in the PDF format
      operationId: loadSystemOperationPdfDocument
      tags:
        - adminReports
      requestBody:
        description: search parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SystemAccountOperationsRequest'
      responses:
        '200':
          description: A PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Exchange ticket not found
        '403':
          description: Authorization information is missing or invalid.
components:
  schemas:
    AccountsReportRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        dateFromUtc:
          type: string
          format: date-time
        dateToUtc:
          type: string
          format: date-time
    AccountsReportResponse:
      type: object
      properties:
        reportDateUtc:
          type: string
          format: date-time
    SystemAccountOperationsRequest:
      type: object
      required:
        - systemAccountId
        - dateFromUtc
      properties:
        dateFromUtc:
          type: string
          format: date
        dateToUtc:
          type: string
          format: date
        systemAccountId:
          description: System account Id
          type: string
          format: uuid