FROM node:alpine AS build

# Setup the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./frontend-admin/package.json ./frontend-admin/package-lock.json ./

# Copy other files and folders to the working directory
COPY ./frontend-admin/ ./

# Install dependencies
RUN npm install

WORKDIR /usr/src/app/frontend-admin/
# Build Angular application in PRODUCTION mode
RUN npm run build --production

# Stage 2: Serve the application using Nginx
FROM nginx:alpine

# Copy built Angular app files to Nginx HTML folder
COPY --from=build /usr/src/app/dist/frontend-admin/browser /usr/share/nginx/html
COPY ./frontend-admin/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./docs/keys/private.pem /etc/nginx/private.pem
COPY ./docs/keys/selfsigned.pem /etc/nginx/selfsigned.pem

# Start Nginx server
CMD ["/bin/sh",  "-c",  "exec nginx-debug -g 'daemon off;'"]
