events{}
  http {
    include /etc/nginx/mime.types;

    server {
      listen 0.0.0.0:4100;
      listen [::]:4100;
      server_name localhost;
      root /usr/share/nginx/html;
      resolver 10.100.0.10 valid=10s;
      index index.html;

      absolute_redirect off;
      add_header x-frame-options "sameorigin" always;

      location / {
        try_files $uri $uri/ /index.html =404;
      }
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
          root /usr/share/nginx/html;
      }

  }
}
