openapi: "3.1.1"
info:
  title: Exchange App Accounts API
  description: This is a REST API for Exchange System application for Accounts Management.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /accounts/list:
    get:
      summary: Load accounts for the user
      operationId: loadAccountBalanceList
      x-application-role: hasAuthority('USER')
      tags:
        - accounts
      responses:
        '200':
          description: Operation completed successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountBalance"
        '403':
          description: Unauthorized request
  /accounts/user/account:
    post:
      summary: Create User Account
      operationId: createUserAccount
      x-application-role: hasAuthority('USER')
      requestBody:
        description: User Account details
        required: true
        content:
          application/json:
            schema:
              type: UserAccount
      tags:
        - accounts
      responses:
        '201':
          description: user account created
          content:
            application/json:
              schema:
                type: UserAccount
        '400':
          description: Returned when unable to create user account.
        '403':
          description: Unauthorized request
    put:
      summary: Update User Account
      operationId: updateUserAccount
      x-application-role: hasAuthority('USER')
      requestBody:
        description: User Account details
        required: true
        content:
          application/json:
            schema:
              type: UserAccount
      tags:
        - accounts
      responses:
        '204':
          description: user account updated
          content:
            application/json:
              schema:
                type: UserAccount
        '403':
          description: Unauthorized request
  /accounts/operations:
    post:
      summary: Get all operations related to the User
      operationId: loadUserOperationList
      x-application-role: hasAuthority('USER')
      requestBody:
        description: account operation request object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountOperationsRequest"
      tags:
        - accounts
      responses:
        '200':
          description: Successfully retrieved all user operations, returning a list of UserOperation objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserOperation
                  description: An array of UserOperation objects, each representing financial operation associated with the user.
        '404':
          description: Error user or account not found.
        '403':
          description: Unauthorized request
  /accounts/withdraw:
    post:
      summary: Save Exchange Ticket
      operationId: saveWithdrawRequest
      x-application-role: hasAuthority('USER')
      requestBody:
        description: new exchange ticket object
        required: true
        content:
          application/json:
            schema:
              type: UserAccountOperation
      tags:
        - accounts
      responses:
        '204':
          description: Operation completed successfully
        '404':
          description: Error user or account not found.
        '400':
          description: Returned when a user has insufficient funds for a money operation.
        '403':
          description: Unauthorized request
  /accounts/bank:
    post:
      summary: Save Bank Account related to the System User Account
      operationId: saveBankAccount
      x-application-role: hasAuthority('USER')
      tags:
        - accounts
      requestBody:
        description: bank account to be saved
        required: true
        content:
          application/json:
            schema:
              type: UserBankAccount
      responses:
        '201':
          description: Bank account is created
          content:
            application/json:
              schema:
                type: UserBankAccount
        '404':
          description: Account not found
        '403':
          description: Unauthorized request
components:
  schemas:
    AccountBalance:
      type: object
      required:
        - currency
        - amount
      properties:
        currency:
          type: string
        amount:
          type: integer
          format: int64
        userAccountId:
          type: string
          format: uuid
    UserBalanceRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        currency:
          type: string
    AccountOperationsRequest:
      type: object
      required:
        - dateFrom
      properties:
        currency:
          type: Currency
        dateFrom:
          type: string
          format: date-time
        dateTo:
          type: string
          format: date-time
        page:
          type: integer
        size:
          type: integer
