openapi: "3.1.1"
info:
  title: Exchange App Accounts API
  description: This is a REST API for Exchange System application for Accounts Management.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /dictionaries/timezones:
    get:
      summary: Load timezone names
      operationId: loadTimezoneList
      tags:
        - dictionaries
      responses:
        '200':
          description: List of timezones
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '403':
          description: Unauthorized request
  /dictionaries/unicodeLocales:
    get:
      summary: Load timezone names
      operationId: loadUnicodeLocalesList
      tags:
        - dictionaries
      responses:
        '200':
          description: List of unicode locales
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '403':
          description: Unauthorized request