openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for the Exchange System application, which allows users to manage their exchange tickets.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: The base URL for the API, pointing to the local server where the application is hosted.
paths:
  /tickets/create:
    post:
      summary: Send Exchange Ticket
      operationId: saveUserTicket
      requestBody:
        description: A JSON object representing a new exchange ticket to be created.
        required: true
        content:
          application/json:
            schema:
              type: UserTicket
              description: The schema for the UserTicket object, which includes details about the ticket being created.
      tags:
        - tickets
      responses:
        '201':
          description: Ticket saved successfully, indicating that the new exchange ticket has been created.
        '400':
          description: Returned when a user has insufficient funds for a money operation, indicating a failure to create the ticket due to financial constraints.
        '403':
          description: unauthorized request
  /tickets/cancel/{ticketId}:
    post:
      summary: Cancel Exchange Ticket
      operationId: cancelExchangeTicket
      parameters:
        - in: path
          name: ticketId
          schema:
            type: integer
          required: true
          description: Numeric ID of the ticket to be canceled
      responses:
        '204':
          description: ticket cancelled
        '404':
          description: ticket not found
        '403':
          description: unauthorized request
  /tickets/list:
    get:
      summary: Get all User Tickets
      operationId: loadUserTicketList
      tags:
        - tickets
      responses:
        '200':
          description: Successfully retrieved all user tickets, returning a list of UserTicket objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserTicket
                  description: An array of UserTicket objects, each representing an exchange ticket associated with the user.
        '403':
          description: unauthorized request