openapi: "3.1.1"
info:
  title: Exchange App
  description: A comprehensive REST API for the Exchange System application, enabling users to manage, create, cancel, and track exchange tickets with secure authentication and authorization mechanisms.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Local development server hosting the Exchange App API, used for testing and development purposes.

paths:
  /tickets/create:
    post:
      summary: Create a New Exchange Ticket
      description: Endpoint for users to create a new exchange ticket, with validation for financial constraints and user authorization.
      operationId: saveUserTicket
      x-application-role: hasAuthority('USER')
      tags:
        - tickets
      requestBody:
        description: Detailed information for creating a new exchange ticket, including all necessary transaction details.
        required: true
        content:
          application/json:
            schema:
              type: UserTicket
              description: Comprehensive ticket creation request containing all required transaction and user-specific information.

      responses:
        '201':
          description: Ticket successfully created and saved in the system. Returns the created ticket's details or confirmation.
        '400':
          description: Bad request due to insufficient funds or invalid ticket parameters. Provides detailed error information about the creation failure.a
        '403':
          description: Authorization failed. User lacks necessary permissions to create a ticket.


  /tickets/cancel:
    post:
      summary: Cancel an Existing Exchange Ticket
      description: Endpoint allowing users to cancel a previously created exchange ticket before its realization.
      operationId: cancelExchangeTicket
      x-application-role: hasAuthority('USER')
      tags:
        - tickets
      requestBody:
        description: Ticket identification details required to cancel a specific exchange ticket.
        required: true
        content:
          application/json:
            schema:
              type: UserTicket
              description: Ticket details necessary for cancellation, primarily focusing on ticket identification.
      responses:
        '204':
          description: Ticket successfully cancelled. No content returned to indicate successful cancellation.
        '404':
          description: Requested ticket not found in the system, potentially already processed or deleted.
        '403':
          description: Authorization failed. User lacks permissions to cancel the specified ticket.

  /tickets/list:
    get:
      summary: Retrieve All User Tickets
      description: Endpoint to fetch a comprehensive list of all exchange tickets associated with the authenticated user.
      operationId: loadUserTicketList
      x-application-role: hasAuthority('USER')
      tags:
        - tickets
      responses:
        '200':
          description: Successfully retrieved all user tickets, returning a list of UserTicket objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: UserTicket
                  description: An array of UserTicket objects, each representing an exchange ticket associated with the user.
        '403':
          description: Unauthorized request
  /tickets/realized:
    get:
      summary: Get all User Tickets
      operationId: loadRealizedTicketList
      x-application-role: hasAuthority('USER')
      tags:
        - tickets
      responses:
        '200':
          description: Successfully retrieved user tickets with status Realized, returning a list of UserTicket objects.
          content:
            application/json:
              schema:
                type: array
                description: Collection of exchange tickets that have been fully processed and completed.
                items:
                  type: UserTicket
                  description: An array of UserTicket objects, each representing an exchange ticket associated with the user.
        '403':
          description: Unauthorized request