FROM openjdk:21-jdk-slim
WORKDIR /app

COPY target/backend-external-*-SNAPSHOT.jar /app/backend-external.jar

ENTRYPOINT ["java", "-Xmx512M", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000", "-jar", "/app/backend-external.jar"]