FROM amazoncorretto:25-jdk
WORKDIR /app

COPY target/backend-external-*.jar /app/backend-external.jar

ENTRYPOINT ["java", "-Xms128M", "-Xmx512M", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8007", "-jar", "/app/backend-external.jar"]